### ISSUE TITLE
Console command module:enable 'MagePsycho_Customshipping'  Module not found

### ISSUE THREAD

**Issue by JakubKontra** [MagePsycho/magento2-custom-shipping#2]
Hi MagePsycho!

I have a small problem with your module. I was trying to enable it and i got this error.

![screen shot 2016-03-24 at 20 10 21](https://cloud.githubusercontent.com/assets/479276/14028409/a73150f6-f1fc-11e5-8e1e-e0bb32558b21.png)

Could you please help me with that? 

Thanks a lot!

**Comment by JakubKontra** [comment]
Dead repo.

**Comment by MagePsycho** [comment]
Make sure you have installed the extension first. You can install the extension either by using composer or zip file as mentioned in https://github.com/MagePsycho/magento2-custom-shipping

Once you have the module codebase in the Magento then only you have to enable the extension (like what you are doing)

Hope this helps.
