### ISSUE TITLE
Not working on magento 2.0.1

### ISSUE THREAD

**Issue by ivansuharyadi** [MagePsycho/magento2-custom-shipping#3]
Im use this extensions, but on page place order, i has error with message :  "Please choose shipping method".

**Comment by MagePsycho** [comment]
This extension was developed in earlier version of Magento2. Will verify and update on the same.

**Comment by rattan2011** [comment]
I have same problem on order placement. Please fix it asap.

**Comment by MagePsycho** [comment]
Fixed in latest commit.

**Comment by Rijisha** [comment]
problem with magento 2.1.0

**Comment by Rijisha** [comment]
Not working on magento 2.1.0. Can you please help
